#!/bin/bash

# mozbuild=~/.mozbuild
# export PATH="$PATH:$mozbuild/git-cinnabar"
# rootDir=$PWD

# if [ ! -d $mozbuild ]; then
#   mkdir $mozbuild
# fi

# cd mozilla-unified

# cp -r ../src/changed/* .
# cp ../src/mozconfig.linux mozconfig

# echo "Applying universal patches"
# for patch in ../src/patches/*.patch; do
#   patch -p1 < $patch
# done
# echo "Done applying universal patches"

# ./mach configure --without-wasm-sandboxed-libraries
# ./mach build
# ./mach package

# cd ..

shopt -s extglob

export MOZBUILD_STATE_PATH=$PWD/.mozbuild
export PATH="$PATH:$mozbuild/git-cinnabar"

cd mozilla-unified

cp -r ../src/changed/* .
cp ../src/mozconfig.linux mozconfig

echo "Applying universal patches"
for patch in ../src/patches/*.patch; do
  patch -p1 < $patch
done
echo "Done applying universal patches"

export CXXFLAGS="-fno-exceptions" 
./mach configure --without-wasm-sandboxed-libraries
./mach build
./mach package

cd ..

rm -r NEUTRON_INTERNAL_APP_NAME-linux
mkdir NEUTRON_INTERNAL_APP_NAME-linux
tar --strip-components=1 -xvf  mozilla-unified/obj-*-pc-linux-gnu/dist/*.tar.@(bz2|xz) -C NEUTRON_INTERNAL_APP_NAME-linux/
cp -r src/distribution/ NEUTRON_INTERNAL_APP_NAME-linux/
mv NEUTRON_INTERNAL_APP_NAME-linux/distribution/policies-flatpak.json NEUTRON_INTERNAL_APP_NAME-linux/distribution/policies.json
cp src/open-in-default-browser/open-in-default-browser NEUTRON_INTERNAL_APP_NAME-linux/open-in-default-browser